name: kgl_time
description: "Arbeitszeiterfassung für die Kirchgemeinde Lauterbrunnen"
publish_to: 'none'

version: 0.3.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  notifying_list: ^0.1.0
  go_router: ^16.2.4
  intl: any
  week_number: ^1.1.1
  isar_community: 3.3.0-dev.1
  isar_community_flutter_libs: 3.3.0-dev.1
  path_provider: ^2.1.5
  path_provider_linux: ^2.2.1
  url_launcher: ^6.3.2
  animated_toggle_switch: ^0.8.5
  timer_builder: ^2.0.0
  collection: any
  #firebase_auth: ^5.5.0
  #google_sign_in: ^6.2.2
  #firebase_core: ^4.2.0
  #googleapis: ^13.2.0
  #extension_google_sign_in_as_googleapis_auth: ^2.0.12
  #googleapis_auth: ^1.6.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: 3.3.0-dev.1
  build_runner: 2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
  - assets/playstore-icon.png
  generate: true
flutter_intl:
  enabled: true
