name: kgl_time
description: "Arbeitszeiterfassung für die Kirchgemeinde Lauterbrunnen"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3

isar_version: &isar_version 3.1.0+1 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  notifying_list: ^0.1.0
  go_router: ^14.2.8
  intl: any
  week_number: ^1.1.0
  #collection: any
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true