name: kgl_time
description: "Arbeitszeiterfassung für die Kirchgemeinde Lauterbrunnen"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  notifying_list: ^0.1.0
  go_router: ^14.2.8
  intl: any
  week_number: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true