name: kgl_time
description: "Arbeitszeiterfassung für die Kirchgemeinde Lauterbrunnen"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  notifying_list: ^0.1.0
  go_router: ^14.3.0
  intl: any
  week_number: ^1.1.0
  #collection: any
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  path_provider: ^2.1.4
  path_provider_linux: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  build_runner: any

flutter:
  uses-material-design: true