// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-Q5mYoGQMGmN3iiOxY3mBV-HVOKRlM8',
    appId: '1:43939542388:web:291f16f597df877537a821',
    messagingSenderId: '43939542388',
    projectId: 'kgl-time',
    authDomain: 'kgl-time.firebaseapp.com',
    storageBucket: 'kgl-time.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaThYFcmIGQA-HQmuPNSteVtrPaMqukyo',
    appId: '1:43939542388:android:89715ce307c24fd537a821',
    messagingSenderId: '43939542388',
    projectId: 'kgl-time',
    storageBucket: 'kgl-time.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-Q5mYoGQMGmN3iiOxY3mBV-HVOKRlM8',
    appId: '1:43939542388:web:4a645a5c28718d6637a821',
    messagingSenderId: '43939542388',
    projectId: 'kgl-time',
    authDomain: 'kgl-time.firebaseapp.com',
    storageBucket: 'kgl-time.firebasestorage.app',
  );

}